import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../api'
import { useAuth } from '../auth'
import { Company, Project, Task, User } from '../types'
import { HEALTH_COLORS, METHODOLOGIES, PROJECT_STATUSES, fmtDate, label } from '../constants'
import SearchableSelect from '../components/SearchableSelect'

const PRIORITIES = ['low', 'medium', 'high', 'critical']
const EMPTY_FORM = {
  name: '', company_id: '', manager_id: '', project_type: 'operational', methodology: 'hybrid',
  status: 'planning', priority: 'medium', start_date: '', baseline_due_date: '', objective: '',
}

// FastAPI sends {"detail": "..."} or a list of validation errors — show it as a readable sentence.
function errText(e: any): string {
  const raw = e?.message ?? String(e)
  try {
    const d = JSON.parse(raw)?.detail
    if (typeof d === 'string') return d
    if (Array.isArray(d)) return d.map((x: any) => `${(x.loc || []).slice(1).join('.')}: ${x.msg}`).join('; ')
  } catch { /* not JSON */ }
  return raw || 'Could not create the project'
}

/** "Add Project" popup. Posts to POST /projects (ProjectBase schema); the project code is generated by the backend. */
function ProjectForm({ companies, users, types, onClose, onSaved }: {
  companies: Company[]; users: User[]; types: string[]; onClose: () => void; onSaved: (p: Project) => void
}) {
  const [form, setForm] = useState({ ...EMPTY_FORM })
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const set = (k: string, v: string) => setForm((f) => ({ ...f, [k]: v }))

  const submit = async () => {
    if (!form.name.trim()) { setError('Project name is required'); return }
    if (form.start_date && form.baseline_due_date && form.start_date > form.baseline_due_date) {
      setError('Start date cannot be after the due date'); return
    }
    setSaving(true)
    setError('')
    try {
      const p = await api.post<Project>('/projects', {
        code: null,
        name: form.name.trim(),
        company_id: form.company_id ? Number(form.company_id) : null,
        manager_id: form.manager_id ? Number(form.manager_id) : null,
        project_type: form.project_type || 'operational',
        methodology: form.methodology,
        status: form.status,
        priority: form.priority,
        objective: form.objective.trim() || null,
        start_date: form.start_date || null,
        baseline_due_date: form.baseline_due_date || null,
        approved_due_date: form.baseline_due_date || null,
      })
      onSaved(p)
    } catch (e: any) {
      setError(errText(e))
    } finally {
      setSaving(false)
    }
  }

  const opts = (list: string[]) => list.map((v) => ({ value: v, label: label(v) }))
  const typeList = Array.from(new Set(['operational', ...types]))

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h2>New Project</h2>
        {error && <div className="badge red" style={{ marginBottom: 12 }}>{error}</div>}

        <label>Project Name *</label>
        <input value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="e.g. Kiln 2 Vibration Monitoring" autoFocus />
        <div className="small muted" style={{ marginTop: 6 }}>Project code is generated automatically.</div>

        <div className="form-row">
          <div>
            <label>Company (SBU)</label>
            <SearchableSelect value={form.company_id} items={companies.map((c) => ({ value: String(c.id), label: c.name }))} onChange={(v) => set('company_id', v)} placeholder="Search company…" />
          </div>
          <div>
            <label>Project Manager</label>
            <SearchableSelect value={form.manager_id} items={users.map((u) => ({ value: String(u.id), label: u.name }))} onChange={(v) => set('manager_id', v)} placeholder="Search person…" />
          </div>
        </div>

        <div className="form-row three">
          <div>
            <label>Type</label>
            <SearchableSelect value={form.project_type} items={opts(typeList)} onChange={(v) => set('project_type', v)} placeholder="Type…" />
          </div>
          <div>
            <label>Methodology</label>
            <SearchableSelect value={form.methodology} items={opts(METHODOLOGIES)} onChange={(v) => set('methodology', v)} placeholder="Methodology…" />
          </div>
          <div>
            <label>Priority</label>
            <SearchableSelect value={form.priority} items={opts(PRIORITIES)} onChange={(v) => set('priority', v)} placeholder="Priority…" />
          </div>
        </div>

        <div className="form-row three">
          <div>
            <label>Status</label>
            <SearchableSelect value={form.status} items={opts(PROJECT_STATUSES)} onChange={(v) => set('status', v)} placeholder="Status…" />
          </div>
          <div>
            <label>Start Date</label>
            <input type="date" value={form.start_date} onChange={(e) => set('start_date', e.target.value)} />
          </div>
          <div>
            <label>Due Date</label>
            <input type="date" value={form.baseline_due_date} onChange={(e) => set('baseline_due_date', e.target.value)} />
          </div>
        </div>

        <label>Objective</label>
        <textarea rows={3} value={form.objective} onChange={(e) => set('objective', e.target.value)} placeholder="What should this project achieve?" />

        <div className="modal-actions">
          <button className="btn" onClick={onClose}>Cancel</button>
          <button className="btn primary" onClick={submit} disabled={saving}>{saving ? 'Saving…' : 'Create Project'}</button>
        </div>
      </div>
    </div>
  )
}

export default function Projects() {
  const { user } = useAuth()
  const isAdmin = user?.role === 'admin'   // only admins get a Delete button (the API enforces this too)
  const [deletingId, setDeletingId] = useState<number | null>(null)
  const [projects, setProjects] = useState<Project[]>([])
  const [tasks, setTasks] = useState<Task[]>([])
  const [users, setUsers] = useState<User[]>([])
  const [companies, setCompanies] = useState<Company[]>([])
  const [filter, setFilter] = useState({ company_id: '', status: '', health: '', type: '', manager_id: '', methodology: '' })
  const [showForm, setShowForm] = useState(false)
  const navigate = useNavigate()

  const reloadProjects = () => api.get<Project[]>('/projects').then(setProjects)

  useEffect(() => {
    reloadProjects()
    api.get<Task[]>('/tasks').then(setTasks)
    api.get<User[]>('/organizations/users').then(setUsers)
    api.get<Company[]>('/organizations/companies').then(setCompanies)
  }, [])

  const open = (p: Project) => navigate(`/projects/${p.id}`)

  // Admin-only. Uses the existing DELETE /projects/{id} route: the backend soft-deletes the project's
  // tasks, detaches milestones/risks/issues/backlog, then removes the project — so no foreign key breaks.
  const removeProject = async (p: Project) => {
    if (!isAdmin || deletingId !== null) return
    const n = tasks.filter((t) => t.project_id === p.id).length
    const warn = n > 0 ? `\n\nIts ${n} task${n === 1 ? '' : 's'} will also be removed from all lists.` : ''
    if (!confirm(`Delete project ${p.code} — "${p.name}"?${warn}\n\nThis cannot be undone.`)) return
    setDeletingId(p.id)
    try {
      await api.del(`/projects/${p.id}`)
      await Promise.all([reloadProjects(), api.get<Task[]>('/tasks').then(setTasks)])
    } catch (e: any) {
      alert(`Could not delete the project: ${errText(e)}`)
    } finally {
      setDeletingId(null)
    }
  }

  const manager = (id?: number) => users.find((u) => u.id === id)?.name

  const filtered = useMemo(() => {
    return projects.filter((p) => {
      if (filter.company_id && String(p.company_id) !== String(filter.company_id)) return false
      if (filter.status && p.status !== filter.status) return false
      if (filter.health && p.health !== filter.health) return false
      if (filter.type && p.project_type !== filter.type) return false
      if (filter.methodology && p.methodology !== filter.methodology) return false
      if (filter.manager_id && String(p.manager_id) !== String(filter.manager_id)) return false
      return true
    })
  }, [projects, filter])

  const isFiltered = filter.company_id || filter.status || filter.health || filter.type || filter.methodology || filter.manager_id

  const companyItems = [{ value: '', label: 'All companies' }, ...companies.map((c) => ({ value: String(c.id), label: c.name }))]
  const statusItems = [{ value: '', label: 'All' }, ...PROJECT_STATUSES.map((s) => ({ value: s, label: label(s) }))]
  const healthItems = [{ value: '', label: 'All' }, ...Object.keys(HEALTH_COLORS).map((h) => ({ value: h, label: label(h) }))]
  const typeItems = [{ value: '', label: 'All' }, ...Array.from(new Set(projects.map((p) => p.project_type))).map((t) => ({ value: t, label: label(t) }))]
  const methodologyItems = [{ value: '', label: 'All' }, ...METHODOLOGIES.map((m) => ({ value: m, label: label(m) }))]
  const managerItems = [{ value: '', label: 'All' }, ...users.map((u) => ({ value: String(u.id), label: u.name }))]

  const companyName = (id?: number) => companies.find((c) => c.id === id)?.name ?? '—'

  return (
    <div>
      <div className="topbar">
        <div>
          <h1>Projects</h1>
          <div className="crumb">Project master with status &amp; health governance</div>
        </div>
        <button className="btn primary" onClick={() => setShowForm(true)}>+ Add Project</button>
      </div>

      <div className="filters">
        <div className="field" style={{ minWidth: 190 }}>
          <label>Company</label>
          <SearchableSelect value={filter.company_id} items={companyItems} onChange={(v) => setFilter({ ...filter, company_id: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 150 }}>
          <label>Status</label>
          <SearchableSelect value={filter.status} items={statusItems} onChange={(v) => setFilter({ ...filter, status: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 140 }}>
          <label>Health</label>
          <SearchableSelect value={filter.health} items={healthItems} onChange={(v) => setFilter({ ...filter, health: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 160 }}>
          <label>Type</label>
          <SearchableSelect value={filter.type} items={typeItems} onChange={(v) => setFilter({ ...filter, type: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 170 }}>
          <label>Methodology</label>
          <SearchableSelect value={filter.methodology} items={methodologyItems} onChange={(v) => setFilter({ ...filter, methodology: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 180 }}>
          <label>Manager</label>
          <SearchableSelect value={filter.manager_id} items={managerItems} onChange={(v) => setFilter({ ...filter, manager_id: v })} placeholder="Type to search…" />
        </div>
        {isFiltered && (
          <button className="btn sm" onClick={() => setFilter({ company_id: '', status: '', health: '', type: '', manager_id: '', methodology: '' })}>
            Clear
          </button>
        )}
      </div>

      <div className="small muted" style={{ margin: '0 0 10px 2px' }}>{filtered.length} of {projects.length} projects</div>

      <div className="card" style={{ padding: 0 }}>
        <table>
          <thead>
            <tr>
              <th>Code</th><th>Project</th><th>Company</th><th>PM</th><th>Type</th><th>Status</th><th>Health</th>
              <th>Completion</th><th>Baseline</th><th>Forecast</th>{isAdmin && <th></th>}
            </tr>
          </thead>
          <tbody>
            {filtered.map((p) => (
              <tr key={p.id} onClick={() => open(p)} style={{ cursor: 'pointer' }}>
                <td className="muted small">{p.code}</td>
                <td>
                  <Link
                    to={`/projects/${p.id}`}
                    style={{ color: 'var(--green)', fontWeight: 600, textDecoration: 'underline' }}
                  >
                    {p.name}
                  </Link>
                </td>
                <td className="small">{companyName(p.company_id)}</td>
                <td className="small">{manager(p.manager_id)}</td>
                <td className="small">{label(p.project_type)}</td>
                <td><span className="badge gray">{label(p.status)}</span></td>
                <td><span className={`health-dot ${HEALTH_COLORS[p.health]}`} /> {label(p.health)}</td>
                <td style={{ minWidth: 100 }}>
                  <div className="progress"><span style={{ width: `${p.completion_pct}%` }} /></div>
                  <span className="small muted">{p.completion_pct}%</span>
                </td>
                <td className="small">{fmtDate(p.baseline_due_date)}</td>
                <td className="small">{fmtDate(p.forecast_due_date)}</td>
                {isAdmin && (
                  <td>
                    <button
                      className="btn sm danger"
                      disabled={deletingId !== null}
                      onClick={(e) => { e.stopPropagation(); removeProject(p) }}
                    >
                      {deletingId === p.id ? 'Deleting…' : 'Delete'}
                    </button>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length === 0 && <div className="empty">No projects match your filters.</div>}
      </div>

      {showForm && (
        <ProjectForm
          companies={companies}
          users={users}
          types={Array.from(new Set(projects.map((p) => p.project_type)))}
          onClose={() => setShowForm(false)}
          onSaved={() => { setShowForm(false); reloadProjects() }}
        />
      )}
    </div>
  )
}