import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '../api'
import { useAuth } from '../auth'
import { Company, Project, Task, User } from '../types'
import { HEALTH_COLORS, METHODOLOGIES, PROJECT_STATUSES, fmtDate, label } from '../constants'
import SearchableSelect from '../components/SearchableSelect'

const PRIORITIES = ['low', 'medium', 'high', 'critical']
const EMPTY_FORM = {
  name: '', company_id: '', manager_id: '', project_type: 'operational', methodology: 'hybrid',
  status: 'planning', priority: 'medium', start_date: '', baseline_due_date: '', objective: '',
}

// FastAPI sends {"detail": "..."} or a list of validation errors — show it as a readable sentence.
function errText(e: any): string {
  const raw = e?.message ?? String(e)
  try {
    const d = JSON.parse(raw)?.detail
    if (typeof d === 'string') return d
    if (Array.isArray(d)) return d.map((x: any) => `${(x.loc || []).slice(1).join('.')}: ${x.msg}`).join('; ')
  } catch { /* not JSON */ }
  return raw || 'Could not create the project'
}

/** "Add Project" popup. Posts to POST /projects (ProjectBase schema); the project code is generated by the backend. */
function ProjectForm({ companies, users, types, onClose, onSaved }: {
  companies: Company[]; users: User[]; types: string[]; onClose: () => void; onSaved: (p: Project) => void
}) {
  const [form, setForm] = useState({ ...EMPTY_FORM })
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const set = (k: string, v: string) => setForm((f) => ({ ...f, [k]: v }))

  const submit = async () => {
    if (!form.name.trim()) { setError('Project name is required'); return }
    if (form.start_date && form.baseline_due_date && form.start_date > form.baseline_due_date) {
      setError('Start date cannot be after the due date'); return
    }
    setSaving(true)
    setError('')
    try {
      const p = await api.post<Project>('/projects', {
        code: null,
        name: form.name.trim(),
        company_id: form.company_id ? Number(form.company_id) : null,
        manager_id: form.manager_id ? Number(form.manager_id) : null,
        project_type: form.project_type || 'operational',
        methodology: form.methodology,
        status: form.status,
        priority: form.priority,
        objective: form.objective.trim() || null,
        start_date: form.start_date || null,
        baseline_due_date: form.baseline_due_date || null,
        approved_due_date: form.baseline_due_date || null,
      })
      onSaved(p)
    } catch (e: any) {
      setError(errText(e))
    } finally {
      setSaving(false)
    }
  }

  const opts = (list: string[]) => list.map((v) => ({ value: v, label: label(v) }))
  const typeList = Array.from(new Set(['operational', ...types]))

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h2>New Project</h2>
        {error && <div className="badge red" style={{ marginBottom: 12 }}>{error}</div>}

        <label>Project Name *</label>
        <input value={form.name} onChange={(e) => set('name', e.target.value)} placeholder="e.g. Kiln 2 Vibration Monitoring" autoFocus />
        <div className="small muted" style={{ marginTop: 6 }}>Project code is generated automatically.</div>

        <div className="form-row">
          <div>
            <label>Company (SBU)</label>
            <SearchableSelect value={form.company_id} items={companies.map((c) => ({ value: String(c.id), label: c.name }))} onChange={(v) => set('company_id', v)} placeholder="Search company…" />
          </div>
          <div>
            <label>Project Manager</label>
            <SearchableSelect value={form.manager_id} items={users.map((u) => ({ value: String(u.id), label: u.name }))} onChange={(v) => set('manager_id', v)} placeholder="Search person…" />
          </div>
        </div>

        <div className="form-row three">
          <div>
            <label>Type</label>
            <SearchableSelect value={form.project_type} items={opts(typeList)} onChange={(v) => set('project_type', v)} placeholder="Type…" />
          </div>
          <div>
            <label>Methodology</label>
            <SearchableSelect value={form.methodology} items={opts(METHODOLOGIES)} onChange={(v) => set('methodology', v)} placeholder="Methodology…" />
          </div>
          <div>
            <label>Priority</label>
            <SearchableSelect value={form.priority} items={opts(PRIORITIES)} onChange={(v) => set('priority', v)} placeholder="Priority…" />
          </div>
        </div>

        <div className="form-row three">
          <div>
            <label>Status</label>
            <SearchableSelect value={form.status} items={opts(PROJECT_STATUSES)} onChange={(v) => set('status', v)} placeholder="Status…" />
          </div>
          <div>
            <label>Start Date</label>
            <input type="date" value={form.start_date} onChange={(e) => set('start_date', e.target.value)} />
          </div>
          <div>
            <label>Due Date</label>
            <input type="date" value={form.baseline_due_date} onChange={(e) => set('baseline_due_date', e.target.value)} />
          </div>
        </div>

        <label>Objective</label>
        <textarea rows={3} value={form.objective} onChange={(e) => set('objective', e.target.value)} placeholder="What should this project achieve?" />

        <div className="modal-actions">
          <button className="btn" onClick={onClose}>Cancel</button>
          <button className="btn primary" onClick={submit} disabled={saving}>{saving ? 'Saving…' : 'Create Project'}</button>
        </div>
      </div>
    </div>
  )
}

export default function Projects() {
  const { user } = useAuth()
  const isAdmin = user?.role === 'admin'   // only admins get a Delete button (the API enforces this too)
  const [deletingId, setDeletingId] = useState<number | null>(null)
  const [projects, setProjects] = useState<Project[]>([])
  const [tasks, setTasks] = useState<Task[]>([])
  const [users, setUsers] = useState<User[]>([])
  const [companies, setCompanies] = useState<Company[]>([])
  const [filter, setFilter] = useState({ company_id: '', status: '', health: '', type: '', manager_id: '', methodology: '' })
  const [showForm, setShowForm] = useState(false)
  const navigate = useNavigate()

  const reloadProjects = () => api.get<Project[]>('/projects').then(setProjects)

  useEffect(() => {
    reloadProjects()
    api.get<Task[]>('/tasks').then(setTasks)
    api.get<User[]>('/organizations/users').then(setUsers)
    api.get<Company[]>('/organizations/companies').then(setCompanies)
  }, [])

  const open = (p: Project) => navigate(`/projects/${p.id}`)

  // Admin-only. Uses the existing DELETE /projects/{id} route: the backend soft-deletes the project's
  // tasks, detaches milestones/risks/issues/backlog, then removes the project — so no foreign key breaks.
  const removeProject = async (p: Project) => {
    if (!isAdmin || deletingId !== null) return
    const n = tasks.filter((t) => t.project_id === p.id).length
    const warn = n > 0 ? `\n\nIts ${n} task${n === 1 ? '' : 's'} will also be removed from all lists.` : ''
    if (!confirm(`Delete project ${p.code} — "${p.name}"?${warn}\n\nThis cannot be undone.`)) return
    setDeletingId(p.id)
    try {
      await api.del(`/projects/${p.id}`)
      await Promise.all([reloadProjects(), api.get<Task[]>('/tasks').then(setTasks)])
    } catch (e: any) {
      alert(`Could not delete the project: ${errText(e)}`)
    } finally {
      setDeletingId(null)
    }
  }

  const manager = (id?: number) => users.find((u) => u.id === id)?.name
  const userName = (id?: number) => users.find((u) => u.id === id)?.name ?? '—'

  // Most projects were created without a Company / Manager; that information
  // lives on their tasks. So a project belongs to a company if the project OR
  // any of its tasks is in that company, and involves an employee if they are
  // its PM / Sponsor / Owner OR Responsible / Accountable / Reviewer on a task.
  const tasksByProject = useMemo(() => {
    const m = new Map<number, Task[]>()
    tasks.forEach((t) => { if (t.project_id) { const l = m.get(t.project_id) ?? []; l.push(t); m.set(t.project_id, l) } })
    return m
  }, [tasks])
  const projectCompanyIds = (p: Project) => {
    const s = new Set<number>()
    if (p.company_id) s.add(p.company_id)
    ;(tasksByProject.get(p.id) ?? []).forEach((t) => { if (t.company_id) s.add(t.company_id) })
    return s
  }
  const projectPeopleIds = (p: Project) => {
    const s = new Set<number>()
    ;[p.manager_id, p.sponsor_id, p.owner_id].forEach((id) => { if (id) s.add(id) })
    ;(tasksByProject.get(p.id) ?? []).forEach((t) => [t.responsible_id, t.accountable_id, t.reviewer_id].forEach((id) => { if (id) s.add(id) }))
    return s
  }

  /** The project's tasks that match the Company / Employee filters. */
  const matchingTasks = (p: Project) => {
    const cid = filter.company_id ? Number(filter.company_id) : null
    const uid = filter.manager_id ? Number(filter.manager_id) : null
    const leadsProject = uid !== null && [p.manager_id, p.sponsor_id, p.owner_id].includes(uid)
    return (tasksByProject.get(p.id) ?? []).filter((t) => {
      if (cid !== null && (t.company_id ?? p.company_id) !== cid) return false
      // a PM / Sponsor / Owner sees all the project's tasks; others only the ones they are on
      if (uid !== null && !leadsProject && ![t.responsible_id, t.accountable_id, t.reviewer_id].includes(uid)) return false
      return true
    })
  }

  const filtered = useMemo(() => {
    return projects.filter((p) => {
      if (filter.company_id && !projectCompanyIds(p).has(Number(filter.company_id))) return false
      if (filter.status && p.status !== filter.status) return false
      if (filter.health && p.health !== filter.health) return false
      if (filter.type && p.project_type !== filter.type) return false
      if (filter.methodology && p.methodology !== filter.methodology) return false
      if (filter.manager_id && !projectPeopleIds(p).has(Number(filter.manager_id))) return false
      return true
    })
  }, [projects, filter, tasksByProject])

  const isFiltered = filter.company_id || filter.status || filter.health || filter.type || filter.methodology || filter.manager_id
  const personOrCompany = Boolean(filter.company_id || filter.manager_id)
  const shownTasks = useMemo(
    () => (personOrCompany ? filtered.flatMap((p) => matchingTasks(p).map((t) => ({ t, p }))) : []),
    [filtered, personOrCompany, filter, tasksByProject],
  )

  // Dropdowns only offer values that actually occur, so every choice shows something.
  const usedCompanyIds = new Set<number>(projects.flatMap((p) => [...projectCompanyIds(p)]))
  const usedPeopleIds = new Set<number>(projects.flatMap((p) => [...projectPeopleIds(p)]))
  const present = (vals: (string | undefined)[], order: readonly string[]) => {
    const s = new Set(vals.filter(Boolean) as string[])
    return [...order.filter((v) => s.has(v)), ...[...s].filter((v) => !order.includes(v))]
  }
  const companyItems = [{ value: '', label: 'All companies' }, ...companies.filter((c) => usedCompanyIds.has(c.id)).map((c) => ({ value: String(c.id), label: c.name }))]
  const statusItems = [{ value: '', label: 'All' }, ...present(projects.map((p) => p.status), PROJECT_STATUSES).map((s) => ({ value: s, label: label(s) }))]
  const healthItems = [{ value: '', label: 'All' }, ...present(projects.map((p) => p.health), Object.keys(HEALTH_COLORS)).map((h) => ({ value: h, label: label(h) }))]
  const typeItems = [{ value: '', label: 'All' }, ...Array.from(new Set(projects.map((p) => p.project_type))).map((t) => ({ value: t, label: label(t) }))]
  const methodologyItems = [{ value: '', label: 'All' }, ...present(projects.map((p) => p.methodology), METHODOLOGIES).map((m) => ({ value: m, label: label(m) }))]
  const managerItems = [{ value: '', label: 'All' }, ...users.filter((u) => usedPeopleIds.has(u.id)).map((u) => ({ value: String(u.id), label: u.name }))]

  // Company column: the project's own company, otherwise the companies of its tasks.
  const companyName = (p: Project) => {
    const names = [...projectCompanyIds(p)].map((id) => companies.find((c) => c.id === id)?.name).filter(Boolean)
    return names.length ? names.join(', ') : '—'
  }

  return (
    <div>
      <div className="topbar">
        <div>
          <h1>Projects</h1>
          <div className="crumb">Project master with status &amp; health governance</div>
        </div>
        <button className="btn primary" onClick={() => setShowForm(true)}>+ Add Project</button>
      </div>

      <div className="filters">
        <div className="field" style={{ minWidth: 190 }}>
          <label>Company</label>
          <SearchableSelect value={filter.company_id} items={companyItems} onChange={(v) => setFilter({ ...filter, company_id: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 150 }}>
          <label>Status</label>
          <SearchableSelect value={filter.status} items={statusItems} onChange={(v) => setFilter({ ...filter, status: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 140 }}>
          <label>Health</label>
          <SearchableSelect value={filter.health} items={healthItems} onChange={(v) => setFilter({ ...filter, health: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 160 }}>
          <label>Type</label>
          <SearchableSelect value={filter.type} items={typeItems} onChange={(v) => setFilter({ ...filter, type: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 170 }}>
          <label>Methodology</label>
          <SearchableSelect value={filter.methodology} items={methodologyItems} onChange={(v) => setFilter({ ...filter, methodology: v })} placeholder="Type to search…" />
        </div>
        <div className="field" style={{ minWidth: 180 }}>
          <label>Employee</label>
          <SearchableSelect value={filter.manager_id} items={managerItems} onChange={(v) => setFilter({ ...filter, manager_id: v })} placeholder="Type to search…" />
        </div>
        {isFiltered && (
          <button className="btn sm" onClick={() => setFilter({ company_id: '', status: '', health: '', type: '', manager_id: '', methodology: '' })}>
            Clear
          </button>
        )}
      </div>

      <div className="small muted" style={{ margin: '0 0 10px 2px' }}>
        {filtered.length} of {projects.length} projects{personOrCompany ? ` · ${shownTasks.length} matching task${shownTasks.length === 1 ? '' : 's'}` : ''}
      </div>

      <div className="card" style={{ padding: 0 }}>
        <table>
          <thead>
            <tr>
              <th>Code</th><th>Project</th><th>Company</th><th>PM</th><th>Tasks</th><th>Type</th><th>Status</th><th>Health</th>
              <th>Completion</th><th>Baseline</th><th>Forecast</th>{isAdmin && <th></th>}
            </tr>
          </thead>
          <tbody>
            {filtered.map((p) => (
              <tr key={p.id} onClick={() => open(p)} style={{ cursor: 'pointer' }}>
                <td className="muted small">{p.code}</td>
                <td>
                  <Link
                    to={`/projects/${p.id}`}
                    style={{ color: 'var(--green)', fontWeight: 600, textDecoration: 'underline' }}
                  >
                    {p.name}
                  </Link>
                </td>
                <td className="small">{companyName(p)}</td>
                <td className="small">{manager(p.manager_id) ?? '—'}</td>
                <td className="small">
                  {personOrCompany
                    ? `${matchingTasks(p).length} of ${(tasksByProject.get(p.id) ?? []).length}`
                    : (tasksByProject.get(p.id) ?? []).length}
                </td>
                <td className="small">{label(p.project_type)}</td>
                <td><span className="badge gray">{label(p.status)}</span></td>
                <td><span className={`health-dot ${HEALTH_COLORS[p.health]}`} /> {label(p.health)}</td>
                <td style={{ minWidth: 100 }}>
                  <div className="progress"><span style={{ width: `${p.completion_pct}%` }} /></div>
                  <span className="small muted">{p.completion_pct}%</span>
                </td>
                <td className="small">{fmtDate(p.baseline_due_date)}</td>
                <td className="small">{fmtDate(p.forecast_due_date)}</td>
                {isAdmin && (
                  <td>
                    <button
                      className="btn sm danger"
                      disabled={deletingId !== null}
                      onClick={(e) => { e.stopPropagation(); removeProject(p) }}
                    >
                      {deletingId === p.id ? 'Deleting…' : 'Delete'}
                    </button>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length === 0 && <div className="empty">No projects match your filters.</div>}
      </div>

      {/* The tasks behind the Company / Employee filter */}
      {personOrCompany && shownTasks.length > 0 && (
        <>
          <div className="section-title">
            Matching Tasks ({shownTasks.length})
            <span className="small muted" style={{ fontWeight: 400, marginLeft: 8 }}>
              {[filter.company_id && companies.find((c) => String(c.id) === filter.company_id)?.name,
                filter.manager_id && users.find((u) => String(u.id) === filter.manager_id)?.name].filter(Boolean).join(' · ')}
            </span>
          </div>
          <div className="card" style={{ padding: 0 }}>
            <table>
              <thead>
                <tr><th>Code</th><th>Task</th><th>Project</th><th>Responsible</th><th>Accountable</th><th>Reviewer</th><th>Status</th><th>Progress</th><th>Due</th></tr>
              </thead>
              <tbody>
                {shownTasks.map(({ t, p }) => (
                  <tr key={t.id} onClick={() => navigate(`/tasks/${t.id}`)} style={{ cursor: 'pointer' }}>
                    <td className="muted small">{t.code}</td>
                    <td><Link to={`/tasks/${t.id}`} onClick={(e) => e.stopPropagation()}>{t.title}</Link></td>
                    <td className="small">{p.name}</td>
                    <td className="small">{userName(t.responsible_id)}</td>
                    <td className="small">{userName(t.accountable_id)}</td>
                    <td className="small">{userName(t.reviewer_id)}</td>
                    <td><span className="badge gray">{label(t.status)}</span></td>
                    <td style={{ minWidth: 90 }}>
                      <div className="progress"><span style={{ width: `${t.progress_pct}%` }} /></div>
                      <span className="small muted">{t.progress_pct}%</span>
                    </td>
                    <td className="small">{fmtDate(t.approved_due_date || t.baseline_due_date)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {showForm && (
        <ProjectForm
          companies={companies}
          users={users}
          types={Array.from(new Set(projects.map((p) => p.project_type)))}
          onClose={() => setShowForm(false)}
          onSaved={() => { setShowForm(false); reloadProjects() }}
        />
      )}
    </div>
  )
}